// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Note struct {
	ID          string     `json:"id"`
	Text        string     `json:"text"`
	Description string     `json:"description"`
	SubNote     []*SubNote `json:"subNote"`
}

type SubNote struct {
	ID          string `json:"id"`
	Text        string `json:"text"`
	Description string `json:"description"`
}

type Todo struct {
	ID          string `json:"id"`
	Text        string `json:"text"`
	Description string `json:"description"`
}
